// <auto-generated />
using System;
using Assessment.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812113619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Assessment.Api.Models.Planning", b =>
                {
                    b.Property<long>("PlanningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanningId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("Assessment.Api.Models.PlanningSlot", b =>
                {
                    b.Property<long>("PlanningId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalancedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OriginalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanningId", "SlotOrder");

                    b.ToTable("PlanningSlot", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanningSlot_BalancedQuantity_NonNegative", "BalancedQuantity >= 0");

                            t.HasCheckConstraint("CK_PlanningSlot_OriginalQuantity_NonNegative", "OriginalQuantity >= 0");
                        });
                });

            modelBuilder.Entity("Assessment.Api.Models.PlanningSlot", b =>
                {
                    b.HasOne("Assessment.Api.Models.Planning", "Planning")
                        .WithMany("Slots")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("Assessment.Api.Models.Planning", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
